
version: "3"

services:
  mysql:
    image: mysql:5
    restart: always
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
    ports:
      - "3306:3306"
    restart: always
  server:
    build: 
      dockerfile: Dockerfile
      context: .
    environment: 
      - PORT=3000
      - DB_HOSTNAME=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PW=root
      - DB_NAME=test
    links:
      - mysql:mysql
    depends_on:
      - mysql
    ports:
      - "${PORT}:3000"